# Generated by Django 4.1.6 on 2023-02-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "tree",
                "verbose_name_plural": "trees",
            },
        ),
        migrations.CreateModel(
            name="PlantedTree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age", models.IntegerField()),
                ("planted_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.DecimalField(decimal_places=0, max_digits=20)),
                ("longitude", models.DecimalField(decimal_places=0, max_digits=20)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.account")),
                ("tree", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.tree")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "planted tree",
                "verbose_name_plural": "planted trees",
                "ordering": ("-planted_at",),
            },
        ),
    ]
