# Generated by Django 4.1.7 on 2023-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_tree_plantedtree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantedtree",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
